name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      database:
        image: bitnami/postgresql
        hostname: rocket_db
        ports:
          - 5432:5432
        environment:
          POSTGRESQL_USERNAME: ${DOCKER_USERNAME}
          POSTGRESQL_PASSWORD: ${DOCKER_PASSWORD}
          POSTGRESQL_DATABASE: ${DOCKER_DATABASE}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mydb?plataforma=public"
